In [1]:
import sys
from collections import OrderedDict
from tqdm.notebook import tqdm
sys.path.append('/workspace/shared_workspace/deep-learning-models/models/vision/detection/')
import tensorflow as tf
import horovod.tensorflow as hvd
hvd.init()
fp16 = True
tf.config.experimental_run_functions_eagerly(True)
tf.config.optimizer.set_experimental_options({"auto_mixed_precision": fp16})
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

In [2]:
from awsdet.datasets.coco import CocoDataset
from awsdet.datasets.data_generator import DataGenerator
from awsdet.datasets.loader.build_loader import build_dataloader

from awsdet.models.backbones import keras_backbone
from awsdet.models.necks import fpn
from awsdet.models.anchor_heads.rpn_head import RPNHead
from awsdet.core.bbox.bbox_target import ProposalTarget
from awsdet.core.mask.mask_target import MaskTarget
from awsdet.models.roi_extractors.roi_align import PyramidROIAlign
from awsdet.models.bbox_heads.bbox_head import BBoxHead
from awsdet.models.mask_heads.mask_head import MaskHead

In [3]:
dataset_dir = '/workspace/shared_workspace/data/coco/coco/'
subset = 'train'
coco_dataset = CocoDataset(dataset_dir, subset, mask=True, train=True)

loading annotations into memory...
Done (t=12.74s)
creating index...
index created!


In [4]:
local_batch_size=1
coco_tdf = build_dataloader(coco_dataset, local_batch_size)[0]

In [5]:
backbone = keras_backbone.KerasBackbone('ResNet50V1')
neck = fpn.FPN()
rpn_head = RPNHead()
bbox_target = ProposalTarget()
bbox_roi_extractor = PyramidROIAlign(pool_shape=[7, 7], pool_type='avg')
mask_roi_extractor = PyramidROIAlign(pool_shape=[14, 14], pool_type='avg')

In [6]:
img, img_metas, gt_boxes, gt_class_ids, gt_masks = next(iter(coco_tdf.prefetch(128)))

Starting new loop for GPU: 0


In [7]:
train_tdf = iter(coco_tdf)

In [9]:
training=True
class Model(tf.keras.Model):
    
    def __init__(self):
        super().__init__()
        self.backbone = keras_backbone.KerasBackbone('ResNet50V1')
        self.neck = fpn.FPN()
        self.rpn_head = RPNHead()
        self.bbox_target = ProposalTarget()
        self.bbox_roi_extractor = PyramidROIAlign(pool_shape=[7, 7], pool_type='avg')
        self.mask_roi_extractor = PyramidROIAlign(pool_shape=[14, 14], pool_type='avg')
        self.bbox_head = BBoxHead(81, (7, 7))
        self.mask_head = MaskHead(81)
        self.mask_target = MaskTarget()
    
    @tf.function(experimental_relax_shapes=True)
    def call(self, img, img_metas, gt_boxes, gt_class_ids, gt_masks, training=True):
        C2, C3, C4, C5 = self.backbone(img, training=training)
        P2, P3, P4, P5, P6 = self.neck((C2, C3, C4, C5), training=training)
        rpn_feature_maps = [P2, P3, P4, P5, P6]
        rcnn_feature_maps = [P2, P3, P4, P5]
        rpn_class_logits, rpn_probs, rpn_deltas = self.rpn_head(rpn_feature_maps, training=training)
        proposals_list = self.rpn_head.get_proposals(
                    rpn_probs, rpn_deltas, img_metas, training=training)
        if training:
            rois_list, rcnn_target_matchs, \
            rcnn_target_deltas, inside_weights, outside_weights, \
            fg_assignments = \
                self.bbox_target.build_targets(proposals_list, gt_boxes, gt_class_ids, img_metas)
        else:
            rois_list = proposals_list
        bbox_pooled_regions_list = self.bbox_roi_extractor(
            (rois_list, rcnn_feature_maps, img_metas), training=training)
        rcnn_class_logits, rcnn_probs, rcnn_deltas = \
            self.bbox_head(bbox_pooled_regions_list, training=training)
        mask_pooled_regions_list = self.mask_roi_extractor(
            (rois_list, rcnn_feature_maps, img_metas), training=training)
        mask_regions, mask_targets = self.mask_target.get_targets(mask_pooled_regions_list, 
                                                   rois_list, gt_masks, fg_assignments, 
                                                   rcnn_target_matchs, img_metas)
        mask_logits = self.mask_head(mask_regions)
        
        rpn_inputs = (rpn_class_logits, rpn_deltas, gt_boxes, gt_class_ids, img_metas)
        rpn_class_loss, rpn_bbox_loss = self.rpn_head.loss(rpn_inputs)
        rcnn_inputs = (rcnn_class_logits, rcnn_deltas, rcnn_target_matchs,
                rcnn_target_deltas, inside_weights, outside_weights)
        rcnn_class_loss, rcnn_bbox_loss = self.bbox_head.loss(rcnn_inputs)
        mask_loss = self.mask_target.loss(mask_logits, mask_targets, rcnn_target_matchs)
        losses_dict = {
                'rpn_class_loss': rpn_class_loss,
                'rpn_bbox_loss': rpn_bbox_loss,
                'rcnn_class_loss': rcnn_class_loss,
                'rcnn_bbox_loss': rcnn_bbox_loss,
                'rcnn_mask_loss': mask_loss
            }
        #return mask_logits, mask_targets, rcnn_target_matchs
        return losses_dict

In [10]:
model = Model()

In [11]:
losses_dict = model(*next(train_tdf), training=True)

Starting new loop for GPU: 0


In [12]:
losses_list = []
for i in tqdm(range(100)):
    batch = next(train_tdf)
    losses_list.append(model(*batch, training=True))

In [2]:
7329*12*1.8/3600

43.974

In [41]:
class MaskTarget:
    
    def __init__(self, cropped_target_size = (28, 28),
                       loss_func=tf.keras.losses.SparseCategoricalCrossentropy()):
        self.crop_size = tf.constant(cropped_target_size)
        self.loss_func = loss_func

    @tf.function(experimental_relax_shapes=True)
    def batch_indices(self, fg_assignments, rcnn_target_matchs, img_metas):
        batch_size = tf.shape(img_metas)[0]
        batch_length = tf.shape(fg_assignments)[0]//batch_size
        batch_indices = tf.gather(tf.cast(tf.repeat(tf.range(batch_size), batch_length), tf.int32), 
                                  tf.squeeze(tf.where(rcnn_target_matchs!=0)))
        gt_indices = tf.cast(tf.gather(fg_assignments, tf.squeeze(tf.where(rcnn_target_matchs!=0))), tf.int32)
        return tf.transpose(tf.stack([batch_indices, gt_indices]))

    @tf.function(experimental_relax_shapes=True)
    def fg_masks(self, gt_masks, fg_assignments, rcnn_target_matchs, img_metas):
        return tf.expand_dims(tf.gather_nd(gt_masks, self.batch_indices(fg_assignments, rcnn_target_matchs, img_metas)), axis=-1)

    @tf.function(experimental_relax_shapes=True)
    def fg_regions(self, mask_pooled_regions_list, rcnn_target_matchs):
        return tf.gather(tf.concat(mask_pooled_regions_list, axis=0), tf.squeeze(tf.where(rcnn_target_matchs!=0)))
    
    @tf.function(experimental_relax_shapes=True)
    def crop_and_resize(self, rois_list, gt_masks, fg_assignments, rcnn_target_matchs, img_metas):
        H = img_metas[0,6]
        W = img_metas[0,7]
        norm_rois = tf.gather(tf.concat(rois_list, axis=0), 
                                tf.squeeze(tf.where(rcnn_target_matchs!=0))) \
                                / tf.stack([H, W, H ,W])
        fg_masks = self.fg_masks(gt_masks, fg_assignments, rcnn_target_matchs, img_metas)
        cropped_targets = tf.image.crop_and_resize(fg_masks, 
                             norm_rois, 
                             tf.range(tf.shape(norm_rois)[0]), 
                             self.crop_size)
        cropped_targets = tf.cast(cropped_targets, tf.int32)
        return cropped_targets
    
    @tf.function(experimental_relax_shapes=True)
    def get_targets(self, mask_pooled_regions_list, rois_list, gt_masks, 
                    fg_assignments, rcnn_target_matchs, img_metas):
        targets = self.crop_and_resize(rois_list, gt_masks, fg_assignments, 
                                       rcnn_target_matchs, img_metas)
        regions = self.fg_regions(mask_pooled_regions_list, rcnn_target_matchs)
        return regions, targets
    
    @tf.function(experimental_relax_shapes=True)
    def loss(self, pred, target, rcnn_target_matchs):
        pred = tf.transpose(pred, perm=[0, 3, 1, 2])
        locations = tf.squeeze(tf.gather(rcnn_target_matchs, tf.where(rcnn_target_matchs!=0)))
        locations = tf.transpose(tf.stack([tf.range(tf.shape(locations)[0]), locations]))
        return tf.gather_nd(pred, locations)
    
class MaskHead(tf.keras.Model):
    def __init__(self, num_classes, depth=4):
        super().__init__()
        self.depth = depth
        input_shape = tf.keras.Input([28, 28, 1])
        self.conv_0 = tf.keras.layers.Conv2D(256, (3, 3), 
                                            padding="same", activation='relu', 
                                            name="mask_conv_0")
        for layer in range(1, self.depth):
            self.__dict__['conv_{}'.format(layer)] = tf.keras.layers.Conv2D(256, (3, 3), 
                                                    padding="same", activation='relu', 
                                                    name="mask_conv_{}".format(layer))
        self.deconv = tf.keras.layers.Conv2DTranspose(256, (2, 2), strides=2, 
                                                activation="relu",
                                                name="mask_deconv")
        self.masks = tf.keras.layers.Conv2D(num_classes, (1, 1), 
                                            strides=1, activation="sigmoid", name="mask")
            
    @tf.function(experimental_relax_shapes=True)
    def call(self, mask_rois, training=True):
        for layer in range(self.depth):
            mask_rois = self.__dict__['conv_{}'.format(layer)](mask_rois)
        mask_rois = self.deconv(mask_rois)
        return self.masks(mask_rois)

In [42]:
mask_target = MaskTarget()
mask_head = MaskHead(81)

In [47]:
regions, targets = mask_target.get_targets(mask_pooled_regions_list, rois_list, gt_masks, fg_assignments, rcnn_target_matchs, img_metas)

In [48]:
predictions = mask_head(regions)

In [49]:
predictions

<tf.Tensor: shape=(4, 28, 28, 81), dtype=float32, numpy=
array([[[[0.37597486, 0.46165082, 0.35752377, ..., 0.5050885 ,
          0.49639308, 0.48447305],
         [0.51802707, 0.4307219 , 0.34199768, ..., 0.4581883 ,
          0.5991325 , 0.6239017 ],
         [0.4627083 , 0.39282265, 0.3443891 , ..., 0.56812364,
          0.5182661 , 0.6498338 ],
         ...,
         [0.5045916 , 0.42004767, 0.17676082, ..., 0.42460737,
          0.5960571 , 0.68809986],
         [0.4666962 , 0.43517637, 0.29683772, ..., 0.6387187 ,
          0.6557646 , 0.5819045 ],
         [0.49889967, 0.4558591 , 0.27515185, ..., 0.51080936,
          0.5761896 , 0.57901704]],

        [[0.5132594 , 0.4037879 , 0.38016027, ..., 0.5256124 ,
          0.5205335 , 0.5200895 ],
         [0.5989387 , 0.38937795, 0.3033399 , ..., 0.6314764 ,
          0.6862128 , 0.49777538],
         [0.6424156 , 0.42526636, 0.31357056, ..., 0.5037085 ,
          0.539139  , 0.47079438],
         ...,
         [0.60844576, 0.3329885

In [ ]:
pred = mask_target.loss(predictions, targets, rcnn_target_matchs)

In [190]:
targets = tf.reshape(targets, -1)
pred = tf.reshape(pred, -1)
pred = tf.transpose(tf.stack([1 - pred, pred]))

In [191]:
tf.keras.losses.SparseCategoricalCrossentropy()(targets, pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7254246>

In [192]:
tf.gather_nd(predictions, locations)

InvalidArgumentError: indices[9] = [9, 37] does not index into param shape [11,28,28,81] [Op:GatherNd]

In [29]:
tf.reshape(tf.transpose(tf.reshape(tf.tile(tf.range(2), [512]), [512, 2])), -1)

<tf.Tensor: shape=(1024,), dtype=int32, numpy=array([0, 0, 0, ..., 1, 1, 1], dtype=int32)>

In [34]:
@tf.function
def batch_count(batch_size, repeats):
    return tf.concat([tf.repeat(i, repeats) for i in range(batch_size)], axis=0)

In [40]:
tf.gather(batch_count(2, 512), tf.squeeze(tf.where(rcnn_target_matchs!=0)))

<tf.Tensor: shape=(16,), dtype=int32, numpy=array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

In [15]:
tf.squeeze(tf.where(rcnn_target_matchs!=0))

<tf.Tensor: shape=(16,), dtype=int64, numpy=
array([  0,   1,   2,   3, 512, 513, 514, 515, 516, 517, 518, 519, 520,
       521, 522, 523])>

In [16]:
tf.gather(tf.concat(rois_list, axis=0), tf.squeeze(tf.where(rcnn_target_matchs!=0)))

<tf.Tensor: shape=(16, 4), dtype=float32, numpy=
array([[221.06992 , 456.7647  , 345.9264  , 549.0271  ],
       [224.29211 , 474.85352 , 339.93106 , 527.5802  ],
       [237.96452 , 793.42017 , 310.80106 , 818.81604 ],
       [715.0024  ,   5.963801, 770.4071  ,  28.432322],
       [201.72339 , 579.794   , 569.4519  , 806.60846 ],
       [246.35315 , 589.04987 , 517.69244 , 812.0991  ],
       [155.88126 , 616.3534  , 591.2737  , 789.6814  ],
       [173.56662 , 613.30304 , 549.78296 , 833.6649  ],
       [253.29303 , 638.742   , 555.3841  , 796.4214  ],
       [243.05148 , 627.30914 , 598.4955  , 765.806   ],
       [165.04272 , 597.0479  , 596.3755  , 752.92847 ],
       [314.59863 , 611.3273  , 683.7969  , 830.27606 ],
       [158.93147 , 600.4821  , 480.85242 , 802.0304  ],
       [208.2381  , 621.34973 , 814.2215  , 769.47485 ],
       [132.95966 , 661.50824 , 701.4819  , 774.52545 ],
       [152.20798 , 617.7173  , 627.2467  , 802.4598  ]], dtype=float32)>

In [35]:
tf.where(tf.reshape(rcnn_target_matchs, [2, 512])!=0)

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[0, 0],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3]])>

In [32]:
tf.gather(tf.concat(mask_pooled_regions_list, axis=0), 
          tf.squeeze(tf.where(rcnn_target_matchs!=0)))

<tf.Tensor: shape=(5, 14, 14, 256), dtype=float32, numpy=
array([[[[-1.20300312e+01,  2.58238935e+00, -6.35264635e+00, ...,
           3.42369032e+00,  8.05296707e+00, -9.55788612e-01],
         [-1.21715355e+01,  1.67522812e+00, -5.89326096e+00, ...,
           2.65098667e+00,  8.39896774e+00, -1.28212869e-01],
         [-1.34285612e+01,  1.07657516e+00, -6.58809137e+00, ...,
           2.73185372e+00,  8.24378395e+00,  5.99050462e-01],
         ...,
         [-1.19593067e+01,  2.56814814e+00, -7.01596260e+00, ...,
           2.34046650e+00,  8.26298523e+00, -1.06420197e-01],
         [-1.03611870e+01,  2.82687163e+00, -6.25982761e+00, ...,
           2.74056482e+00,  8.06267834e+00, -1.78712666e-01],
         [-1.01709194e+01,  2.56229544e+00, -5.93952036e+00, ...,
           2.64149570e+00,  8.19792557e+00, -6.38368487e-01]],

        [[-1.04787083e+01,  2.95771599e+00, -6.02308846e+00, ...,
           2.85633206e+00,  6.98382330e+00, -3.49115133e-01],
         [-7.99249935e+00,  2.

In [23]:
tf.where(rcnn_target_matchs!=0)

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[  0],
       [512],
       [513],
       [514],
       [515]])>

In [74]:
@tf.function
def mask_loss(target_masks, pred_masks, rcnn_target_matchs, img_metas):
    batch_size = tf.shape(img_metas)[0]
    splits = tf.cast(tf.repeat(tf.shape(rcnn_target_matchs)[0]/batch_size, batch_size), tf.int32)
    mask_indices = tf.where(tf.stack(tf.split(rcnn_target_matchs, splits))!=0)
    targets = tf.gather_nd(target_masks, mask_indices)
    predictions = tf.gather_nd(pred_masks, mask_indices)
    targets = tf.reshape(targets, [-1])
    predictions = tf.reshape(predictions, [-1])
    predictions = tf.transpose(tf.stack([1-predictions, predictions]))
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False) \
                    (targets, predictions)
    return batch_size

In [78]:
%time
mask_loss(target_masks, pred_masks, rcnn_target_matchs, img_metas)

CPU times: user 16 µs, sys: 2 µs, total: 18 µs
Wall time: 37 µs


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
proposals_list, gt_boxes, gt_class_ids, img_metas = model(*next(train_tdf))

In [47]:
import numpy as np
from awsdet.models.utils.misc import calc_pad_shapes, trim_zeros
from awsdet.core.bbox import geometry, transforms

In [53]:
idx = 1
proposals, _ = trim_zeros(proposals_list[idx])
gt_box, non_zeros = trim_zeros(gt_boxes[idx])
gt_box = tf.cast(gt_box, proposals.dtype)
gt_labels = tf.boolean_mask(gt_class_ids[idx], non_zeros)
noise_mean = 5.0
noisy_gt_boxes = tf.add(gt_box, 
                    tf.random.truncated_normal(tf.shape(gt_box), 
                                               noise_mean, 0.1, dtype=proposals.dtype))
proposals_gt = tf.concat([proposals, noisy_gt_boxes], axis=0)
iou = geometry.compute_overlaps(proposals_gt, gt_box)
max_overlaps = tf.reduce_max(iou, axis=1)
gt_assignment = tf.argmax(iou, axis=1)

In [54]:
np.unique(gt_assignment.numpy())

array([0, 1, 2, 3])

In [ ]:
training=True
class Model(tf.keras.Model):
    
    def __init__(self):
        super().__init__()
        self.backbone = keras_backbone.KerasBackbone('ResNet50V1')
        self.neck = fpn.FPN()
        self.rpn_head = RPNHead()
        self.bbox_target = ProposalTarget()
        self.bbox_roi_extractor = PyramidROIAlign(pool_shape=[14, 14], pool_type='avg')
        self.bbox_head = BBoxHead(81, (14, 14))
    def call(self, img, img_metas, gt_boxes, gt_class_ids, training=True):
        C2, C3, C4, C5 = self.backbone(img, training=training)
        P2, P3, P4, P5, P6 = self.neck((C2, C3, C4, C5), training=training)
        rpn_feature_maps = [P2, P3, P4, P5, P6]
        rcnn_feature_maps = [P2, P3, P4, P5]
        rpn_class_logits, rpn_probs, rpn_deltas = self.rpn_head(rpn_feature_maps, training=training)
        proposals_list = self.rpn_head.get_proposals(
                    rpn_probs, rpn_deltas, img_metas, training=training)
        if training:
            rois_list, rcnn_target_matchs, rcnn_target_deltas, inside_weights, outside_weights = \
                self.bbox_target.build_targets(proposals_list, gt_boxes, gt_class_ids, img_metas)
        else:
            rois_list = proposals_list
        pooled_regions_list = self.bbox_roi_extractor(
            (rois_list, rcnn_feature_maps, img_metas), training=training)
        rcnn_class_logits, rcnn_probs, rcnn_deltas = \
            self.bbox_head(pooled_regions_list, training=training)
        rpn_inputs = (rpn_class_logits, rpn_deltas, gt_boxes, gt_class_ids, img_metas)
        rpn_class_loss, rpn_bbox_loss = self.rpn_head.loss(rpn_inputs)
        rcnn_inputs = (rcnn_class_logits, rcnn_deltas, rcnn_target_matchs,
                rcnn_target_deltas, inside_weights, outside_weights)
        rcnn_class_loss, rcnn_bbox_loss = self.bbox_head.loss(rcnn_inputs)
        losses_dict = {
                'rpn_class_loss': rpn_class_loss,
                'rpn_bbox_loss': rpn_bbox_loss,
                'rcnn_class_loss': rcnn_class_loss,
                'rcnn_bbox_loss': rcnn_bbox_loss
            }
        return losses_dict

In [ ]:
def parse_losses(losses, local_batch_size):
    log_vars = OrderedDict()
    for loss_name, loss_value in losses.items():
        if tf.is_tensor(loss_value):
            log_vars[loss_name] = tf.reduce_mean(loss_value)
        elif isinstance(loss_value, list):
            log_vars[loss_name] = tf.add_n(
                [tf.reduce_mean(_loss) for _loss in loss_value])
        else:
            raise TypeError(
                '{} is not a tensor or list of tensors'.format(loss_name))
    loss_list = []
    for _key, _value in log_vars.items():
        if 'loss' in _key:
            if 'reg_loss' not in _key:
                loss_list.append(_value/local_batch_size) # horovod averages (not sums) gradients by default over workers
            else:
                loss_list.append(_value)
    total_loss = sum(loss_list) 
    log_vars['loss'] = total_loss
    return total_loss, log_vars



In [ ]:
model = Model()
train_tdf = iter(coco_tdf)
loss = model(*next(train_tdf))
optimizer = tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.7, nesterov=False)

In [ ]:
@tf.function(experimental_relax_shapes=True)
def train_step(img, img_metas, gt_boxes, gt_class_ids):
    with tf.GradientTape() as tape:
        losses = model(img, img_metas, gt_boxes, gt_class_ids)
        reg_losses = tf.add_n(model.losses)
        losses['reg_loss'] = reg_losses
        loss, log_vars = parse_losses(losses, local_batch_size)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

In [ ]:
progressbar = tqdm(range(10000))

for i in progressbar:
    loss = train_step(*next(train_tdf))
    progressbar.set_description("Loss: {0:.3f}".format(loss))